spring:
  datasource:
    url: jdbc:postgresql://postgres-container-personapi:5432/personapidb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true